-- Seed sample data for Glow Store (idempotent)
-- NOTE: Replace PASSWORD_HASH_PLACEHOLDER with a real hash generated by
-- `php scripts/generate_admin_hash.php your_password` before importing.

-- Admin (insert if not exists)
INSERT INTO admins (email, password_hash, created_at)
SELECT * FROM (
	SELECT 'admin@glowstore.test' AS email, '$2y$12$YsJEkTd4snBn95MgtAA1UeZ3rpcRUz7n0Ev57ZmQ0T3iYiWH/fBcy' AS password_hash, NOW() AS created_at
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM admins WHERE email = 'admin@glowstore.test') LIMIT 1;

-- Categories (insert if not exists)
INSERT INTO categories (name, created_at)
SELECT * FROM (SELECT 'Maquillage' AS name, NOW() AS created_at) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Maquillage') LIMIT 1;
INSERT INTO categories (name, created_at)
SELECT * FROM (SELECT 'Soins' AS name, NOW() AS created_at) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Soins') LIMIT 1;
INSERT INTO categories (name, created_at)
SELECT * FROM (SELECT 'Parfums' AS name, NOW() AS created_at) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Parfums') LIMIT 1;

-- Products (insert if not exists by name)
INSERT INTO products (category_id, name, description, price, stock, image, created_at)
SELECT c.id, 'Rouge à lèvres Glam', 'Rouge à lèvres longue tenue', 12.90, 50, 'glam_lip.jpg', NOW()
FROM categories c
WHERE c.name = 'Maquillage'
	AND NOT EXISTS (SELECT 1 FROM products WHERE name = 'Rouge à lèvres Glam')
LIMIT 1;

INSERT INTO products (category_id, name, description, price, stock, image, created_at)
SELECT c.id, 'Crème hydratante', 'Hydratation 24h', 18.50, 30, 'cream.jpg', NOW()
FROM categories c
WHERE c.name = 'Soins'
	AND NOT EXISTS (SELECT 1 FROM products WHERE name = 'Crème hydratante')
LIMIT 1;

-- Seller (insert if not exists)
INSERT INTO sellers (name, email, password_hash, created_at)
SELECT * FROM (SELECT 'Boutique Demo' AS name, 'seller@glowstore.test' AS email, '$2y$12$23tfGjSeK6bEdps69ZNWvOsutV/W/n.SM4R2vSwT7Ad89glFv5HUG' AS password_hash, NOW() AS created_at) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM sellers WHERE email = 'seller@glowstore.test') LIMIT 1;

-- Link first product to seller (by names)
UPDATE products p
JOIN sellers s ON s.email = 'seller@glowstore.test'
JOIN categories c ON c.name = 'Maquillage'
SET p.seller_id = s.id
WHERE p.name = 'Rouge à lèvres Glam' AND (p.seller_id IS NULL OR p.seller_id = 0);
